# Site settings
title: David Hope
email: dhope@sfu.ca
url: https://dhope.github.io
description: "PhD Candidate working on using migratory decisions in sandpipers to assess population status"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/3454106?v=3&s=460

# Footer settings
footer: David Hope

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/hopethoughts
 # - title: stack-overflow
 #   url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: https://github.com/dhope

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#baseurl: "/SFU_prog_group"


# Build settings
markdown: redcarpet
#kramdown
#permalink: pretty
permalink: /:title/

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
